_format_version: "3.0"
services:
- connect_timeout: 60000
  enabled: true
  host: 192.168.3.7
  name: userService
  port: 8010
  protocol: http
  read_timeout: 60000
  retries: 5
  routes:
  - https_redirect_status_code: 426
    name: userRoute
    path_handling: v0
    paths:
    - /api/users
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: true
  write_timeout: 60000
