_format_version: "3.0"
consumers:
  - username: anonymous_user
  - acls:
      - group: authenticated_users
    jwt_secrets:
      - algorithm: HS512
        key: wQkDdN53pk2voNJX5scgme8aNaAUh0ct
        secret: HvtqM5Exc9QqLKY61fPHuU85nPAJyuoo
    username: linkme-userConsumer
services:
  - connect_timeout: 60000
    enabled: true
    host: linkme-userServer
    name: linkme-userService
    plugins:
      - config:
          anonymous: b9a90efe-400a-4af2-9378-25059734880a
          claims_to_verify: null
          cookie_names: []
          header_names:
            - authorization
          key_claim_name: iss
          maximum_expiration: 0
          run_on_preflight: true
          secret_is_base64: false
          uri_param_names:
            - jwt
        enabled: true
        name: jwt
        protocols:
          - grpc
          - grpcs
          - http
          - https
    port: 80
    protocol: http
    read_timeout: 60000
    retries: 5
    routes:
      - https_redirect_status_code: 426
        id: 1b705633-f4b0-4a1d-b097-e1743af29825
        methods:
          - POST
        path_handling: v0
        paths:
          - /api/users/nocheck
        preserve_host: false
        protocols:
          - http
          - https
        regex_priority: 0
        request_buffering: true
        response_buffering: true
        strip_path: true
      - https_redirect_status_code: 426
        name: linkme-userRoute
        path_handling: v0
        paths:
          - /api/users
        plugins:
          - config:
              allow:
                - authenticated_users
              deny: null
              hide_groups_header: false
            enabled: true
            name: acl
            protocols:
              - grpc
              - grpcs
              - http
              - https
        preserve_host: false
        protocols:
          - http
          - https
        regex_priority: 0
        request_buffering: true
        response_buffering: true
        strip_path: true
    write_timeout: 60000
upstreams:
  - algorithm: round-robin
    hash_fallback: none
    hash_on: none
    hash_on_cookie_path: /
    healthchecks:
      active:
        concurrency: 10
        healthy:
          http_statuses:
            - 200
            - 302
          interval: 0
          successes: 0
        http_path: /
        https_verify_certificate: true
        timeout: 1
        type: http
        unhealthy:
          http_failures: 0
          http_statuses:
            - 429
            - 404
            - 500
            - 501
            - 502
            - 503
            - 504
            - 505
          interval: 0
          tcp_failures: 0
          timeouts: 0
      passive:
        healthy:
          http_statuses:
            - 200
            - 201
            - 202
            - 203
            - 204
            - 205
            - 206
            - 207
            - 208
            - 226
            - 300
            - 301
            - 302
            - 303
            - 304
            - 305
            - 306
            - 307
            - 308
          successes: 0
        type: http
        unhealthy:
          http_failures: 0
          http_statuses:
            - 429
            - 500
            - 503
          tcp_failures: 0
          timeouts: 0
      threshold: 0
    name: linkme-userServer
    slots: 10000
    targets:
      - target: 192.168.3.7:8010
        weight: 100
    use_srv_name: false