apiVersion: v1
kind: Service
metadata:
  name: forum-record-etcd
spec:
  selector:
    app: forum-record-etcd
  ports:
    - protocol: TCP
      port: 12379
      targetPort: 2379
      nodePort: 30883
  type: NodePort
