apiVersion: v1
kind: PersistentVolume
metadata:
  name: forum-etcd-pv
spec:
  storageClassName: record
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/etcd" # 注意此处的挂在点要有读写权限
