apiVersion: apps/v1
kind: Deployment
metadata:
  name: forum-prometheus
  labels:
    app: forum-prometheus
  namespace: forum
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forum-prometheus
  template:
    metadata:
      name: forum-prometheus
      labels:
        app: forum-prometheus
    spec:
      containers:
        - name: forum-prometheus
          image: bitnami/prometheus:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsGroup: 0
            runAsUser: 0
          ports:
            - containerPort: 9090
          volumeMounts:
            - mountPath: /bitnami/prometheus/data
              name: prometheus-data
            - mountPath: /etc/prometheus/prometheus.yml
              name: prometheus-yml
      volumes:
        - name: prometheus-data
          persistentVolumeClaim:
            claimName: forum-prometheus-pvc
        - name: prometheus-yml
          hostPath:
            path: /data/prometheus/prometheus.yml
      restartPolicy: Always
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: forum-prometheus-pv
  namespace: forum
spec:
  storageClassName: record
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/prometheus"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: forum-prometheus-pvc
  namespace: forum
spec:
  storageClassName: record
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: forum-prometheus
  namespace: forum
spec:
  selector:
    app: forum-prometheus
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 30900
  type: NodePort
