global:
alerting:
  alertmanagers:
    - static_configs:
        - targets:
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "forum"
    static_configs:
      - targets: ["192.168.3.54:9090"]