server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    source: root:root@tcp(localhost:3306)/test?parseTime=True&loc=Local
  redis:
    addr: 127.0.0.1:6379
  etcd:
    endpoints:
      - 127.0.0.1:2379
    timeout: 5s