trace:
  endpoint: http://100.64.1.1:30807/api/traces
server:
  http:
    addr: "0.0.0.0:8020"
    timeout: 1s
  grpc:
    addr: "0.0.0.0:9020"
    timeout: 1s
data:
  database:
    source: root:root@tcp(localhost:13306)/linkme_microservices?parseTime=True&loc=Local
  redis:
    addr: "localhost:6379"
  mongo:
    addr: "mongodb://root:root@localhost:27017"
  kafka:
    addr:
      - "localhost:9092"
service:
  etcd:
    addr:
      - "127.0.0.1:2379"
    timeout: 5s